export const START_SET_PAST_DATE = 'START_SET_PAST_DATE';
export const SET_PAST_DATE = 'SET_PAST_DATE';
export const SUCCESS_SET_PAST_DATE = 'SUCCESS_SET_PAST_DATE';
export const ERROR_SET_PAST_DATE = 'ERROR_SET_PAST_DATE';